### PR TITLE
Committee spending

### PR DESCRIPTION
**Pull request by leggitta**
Python notebooks for population level analysis of committees. For each unique committee id, I count the number of filings, and compute the total amount spent.

NOTE: I encountered some negative values in contributions. Not sure if this is a bug in my code or in the data.

### CODE REVIEW

**Comment by leggitta** [comment]
Went a little nuts and organized ```filings.csv``` and ```expenditures.csv``` into a mysql database on my local machine. I provided the code to reproduce the database. Also included a notebook to query the database in python and plot the annual expenditures of the top 10 spending committees.

**Comment by restrellado** [comment]
@leggitta Hello! I'm getting ready to merge but I had one idea. Can you please put your file in a folder that is named in a way that describes what the contents do? That should make it easier for folks to follow. This is especially useful if you plan on adding more files. An example might be `population_analysis_python`.

**Comment by leggitta** [comment]
Thanks @restrellado ! I changed the naming structure and generally tried to make things more readable. lmk what you think.

**Comment by restrellado** [comment]
Looking good! Thank you again for you work on this.

**Pull request merged**
